project:
  type: website

website:
  title: "Enlighten your clock: How your body tells time"
  site-url: enlightenyourclock.org
  page-footer:
    center: |
      [![](assets/logo-mpi.png){width=180pt}](https://www.kyb.tuebingen.mpg.de/en)
    right: "[Imprint](imprint.qmd)"
    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    

execute:
  freeze: auto

  
date: last-modified

language:
  title-block-published: "Last modified:"

